use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :epjs_app, EpjsApp.Endpoint,
  server: true, # see: https://stackoverflow.com/a/44855391/1148249
  root: ".",
  version: Mix.Project.config[:version],
  http: [port: 5000],
  debug_errors: true,
  url: [host: "localhost"],
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# Do not print debug messages in production
config :logger, level: :info


config :epjs_app, EpjsApp.Repo,
  adapter: MssqlEcto,
  hostname: System.get_env("READ_ONLY_HOSTNAME"),
  username: System.get_env("READ_ONLY_USERNAME"),
  password: System.get_env("READ_ONLY_PASSWORD"),
  database: System.get_env("READ_ONLY_DATABASE")

# Finally import the config/prod.secret.exs
# which should be versioned separately.
# import_config "prod.secret.exs"

config :epjs_app, :environment, :prod
